# Generated by Django 4.0 on 2021-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('organizer', '0002_rename_desciption_startup_description'),
	]

	operations = [
		migrations.AlterField(
			model_name='startup',
			name='founded_date',
			field=models.DateField(help_text='Date format: DD/MM/YYYY'),
		),
	]
