# Generated by Django 4.0 on 2021-12-22 19:13

from django.db import migrations


TAGS = (
	{'name': 'aumented reality', 'slug': 'aumented-reality'},
)

def add_tag_data(apps, schema_editor):
	Tag = apps.get_model('organizer', 'Tag')
	for tag in TAGS:
		try:
			tag_object = Tag.objects.create(
				name = tag.get('name'),
				slug = tag.get('slug'),
			)
		except:
			tag_object = Tag.objects.get(
				slug = tag.get('slug')
			)
		tag_object.save()


def remove_tag_data(apps, schema_editor):
	Tag = apps.get_model('organizer', 'Tag')
	for tag in TAGS:
		Tag.objects.get(slug=tag.get('slug')).delete()


class Migration(migrations.Migration):

	dependencies = [
		('organizer', '0003_alter_startup_founded_date'),
	]

	operations = [
		migrations.RunPython(
			add_tag_data,
			remove_tag_data,
		)
	]
