# Generated by Django 4.0 on 2021-12-22 19:40

from django.db import migrations
from datetime import date


STARTUPS = (
	{
		'name': 'CANVA',
		'slug': 'canva',
		 'description': 'Canva is a graphic design platform, used to create social media graphics, presentations, posters, documents and other visual content.',
		'founded_date': date(2013, 12, 22),
		'contact': 'canva_team@example.com',
		'website': 'www.canva.com',
		'tags': [
			{'name': 'design', 'slug': 'design'},
			{'name': 'software', 'slug': 'software'},
		],
	},
)


def add_startup_data(apps, schema_editor):
	Startup = apps.get_model('organizer', 'Startup')
	Tag = apps.get_model('organizer', 'Tag')
	for startup in STARTUPS:
		startup_object = Startup.objects.create(
			name = startup.get('name'),
			slug = startup.get('slug'),
			description = startup.get('description'),
			founded_date = startup.get('founded_date'),
			contact = startup.get('contact'),
			website = startup.get('website'),
		)
		for tag in startup.get('tags'):
			try:
				tag_object = Tag.objects.create(
					name = tag.get('name'),
					slug = tag.get('slug'),
				)
			except:
				tag_object = Tag.objects.get(
					slug__iexact=tag.get('slug')
				)
			startup_object.tags.add(tag_object)
			startup_object.save()


def remove_startup_data(apps, schema_editor):
	Startup = apps.get_model('organizer', 'Startup')
	for startup in STARTUPS:
		Startup.objects.get(
			slug = startup.get('slug')
		).delete()


class Migration(migrations.Migration):

	dependencies = [
		('organizer', '0004_tag_data'),
	]

	operations = [
		migrations.RunPython(
			add_startup_data,
			remove_startup_data,
		)
	]
