# Generated by Django 4.0 on 2021-12-23 00:54

from django.db import migrations
from datetime import date


NEWSLINKS = (
	{
		'title': 'NewsLink Example',
		'pub_date': date(2021, 12, 22),
		'link': 'newslink@example.com',
		'startups': [
			{
				'name': 'startup for newslink example',
				'slug': 'startup-for-newslink-example',
				'founded_date': date(2021, 12, 23),
			},
		],
	},
)


def add_newslink_data(apps, schema_editor):
	NewsLink = apps.get_model('organizer', 'NewsLink')
	Startup = apps.get_model('organizer', 'Startup')
	for newslink in NEWSLINKS:
		for startup in newslink.get('startups'):
			try:
				startup_object = Startup.objects.create(
					name = startup.get('name'),
					slug = startup.get('slug'),
					founded_date = startup.get('founded_date'),
				)
			except:
				startup_object = Startup.objects.get(
					slug = startup.get('slug')
				)
		newslink_object = NewsLink.objects.create(
			title = newslink.get('title'),
			pub_date = newslink.get('pub_date'),
			link = newslink.get('link'),
			startup = startup_object,
		)
		newslink_object.save()


def remove_newslink_data(apps, schema_editor):
	NewsLink = apps.get_model('organizer', 'NewsLink')
	for newslink in NEWSLINKS:
		newslink_object = NewsLink.objects.get(
			slug = newslink.get('slug')
		)
		newslink_object.delete()


class Migration(migrations.Migration):

	dependencies = [
		('organizer', '0005_startup_data'),
	]

	operations = [
		migrations.RunPython(
			add_newslink_data,
			remove_newslink_data,
		),
	]
