# Generated by Django 4.0 on 2021-12-23 16:24

from django.db import migrations, models
from django.utils.text import slugify


SLUG_MAX_LENGHT = 63

def add_slug_data(apps, schema_editor):
	NewsLink = apps.get_model('organizer', 'NewsLink')
	newslink_queryset = NewsLink.objects.all()
	for newslink in newslink_queryset:
		spected_slug = slugify(newslink.title)
		rivals = NewsLink.objects.filter(
			startup = newslink.startup,
			slug__istartswith = spected_slug,
		).count()
		if rivals > 0:
			str_lenght = (
				SLUG_MAX_LENGHT - len(str(rivals))
			)
			newslink.slug = f'{spected_slug[:str_lenght - 1]}-{rivals+1}'
		else:
			newslink.slug = spected_slug
		newslink.save()


def remove_slug_data(apps, schema_editor):
	NewsLink = apps.get_model('organizer', 'NewsLink')
	NewsLink.objects.update(slug='')


class Migration(migrations.Migration):

	dependencies = [
		('organizer', '0006_newslink_data'),
	]

	operations = [
		migrations.AddField(
			model_name = 'newslink',
			name = 'slug',
			field = models.SlugField(
				max_length = SLUG_MAX_LENGHT,
				default = ''
			),
		),
		migrations.RunPython(
			add_slug_data,
			reverse_code = remove_slug_data,
		),
		migrations.AlterField(
			model_name = 'newslink',
			name = 'slug',
			field = models.SlugField(
				max_length = SLUG_MAX_LENGHT
			),
		),
	]
